### PR TITLE
Feature: use hatch environments and scripts

### PR DESCRIPTION
**Pull request by devkral**
Changes:
- use hatch environments and provide scripts
- remove unused dependencies like mock (in stdlib)
- replace multiple linters+isort with ruff and use newest version of ruff 
- remove makefile
- -remove most scripts and replace them with hatch scripts

How to run the hatch scripts:

`hatch run test:test` for example

### CODE REVIEW

**Comment by devkral** [comment]
I hope it can help you. Maybe we can replace the cruft in your other repos.
Anyway why replacing ... with ruff:
"The Ruff formatter is designed to be a drop-in replacement for [Black](https://github.com/psf/black)."

And it is not just a replacement for this, it can also replace isort.

Note: I didn't use the linter because it would cause changes in nearly all files. Should be another commit / PR

**Comment by devkral** [comment]
added a script for type checking with mypy. There are many errors

**Comment by devkral** [comment]
default is  a special environment in hatch. It is used by default

**Comment by tarsil** [comment]
@devkral this is actually great! But the docs also need to be updated, specially the contributing part of this?

**Comment by devkral** [comment]
done, I added also the feature to add arguments to test and lint

**Pull request merged**
